models/CatToItem.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "cat_to_item".
 *
 * @property int $id
 * @property int $item_id
 * @property int $category_id
 */
class CatToItem extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'cat_to_item';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['item_id', 'category_id'], 'required'],
            [['item_id', 'category_id'], 'integer'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'item_id' => 'Item ID',
            'category_id' => 'Category ID',
        ];
    }
}

models/Category.php
<?php

namespace app\models;

use phpDocumentor\Reflection\Types\Object_;
use Yii;
use yii\db\Exception;

/**
 * This is the model class for table "category".
 *
 * @property int $id
 * @property string|null $name
 * @property int|null $original_id
 * @property int|null $original_parent_id
 */
class Category extends \yii\db\ActiveRecord
{

    const DEFAULT_CATEGORY_ID = 2463;

    private static $categories;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['original_id', 'original_parent_id'], 'integer'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'original_id' => 'Original ID',
            'original_parent_id' => 'Original Parent ID',
        ];
    }


    /**
     * @throws Exception
     */
    public static function loadFromXlm($xml)
    {
        if (empty($xml->shop->categories->category)) {
            return false;
        }

        Category::deleteAll();

        foreach ($xml->shop->categories->category as $category) {
            $model = new static();
            $model->name = (string) $category;
            $model->original_id = $category['id'] ?: NULL;
            $model->original_parent_id = $category['parentId'] ?: NULL;
            $model->validate();

            if (! $model->save()) {
                throw new Exception('Ошибка при сохранении категории.');
            }
        }

        return true;
    }


    public static function getCategories()
    {
        if (empty(static::$categories)) {
            static::$categories = array_column(static::find()->all(), NULL, 'original_id');
        }

        return static::$categories;
    }


    public static function getChildId($id)
    {
        $category = Category::getCategories();

        $categoriesId = [$id];
        while (! empty($category[$id]['original_parent_id'])) {
            $id = $category[$id]['original_parent_id'];
            $categoriesId[] = $id;
        }

        return $categoriesId;
    }


    public function getCatToItem()
    {
        return $this->hasOne(CatToItem::class, ['category_id' => 'original_id']);
    }

}

models/Items.php
<?php

namespace app\models;

use Yii;
use yii\db\Exception;

/**
 * This is the model class for table "items".
 *
 * @property int $id
 * @property string $title
 * @property float $price
 * @property float|null $old_price
 * @property string|null $description
 * @property string|null $images
 * @property string|null $other_data
 */
class Items extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'items';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'price'], 'required'],
            [['price', 'old_price'], 'number'],
            [['description', 'other_data'], 'string'],
            [['title', 'images'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'price' => 'Price',
            'old_price' => 'Old Price',
            'description' => 'Description',
            'images' => 'Images',
            'other_data' => 'Other Data',
        ];
    }


    /**
     * @throws Exception
     */
    public static function extractOfferAndRelated($xml)
    {

        if (empty($xml->shop->offers)) {
            return false;
        }

        Items::deleteAll();
        CatToItem::deleteAll();

        foreach ($xml->shop->offers->offer as $offer) {
            $model = new static();
            $model->title = (string) $offer->name;
            $model->price = (string) $offer->price;
            $model->old_price = 0;
            $model->description = (string) $offer->description;
            $model->images = (string) $offer->picture;
            $model->other_data = json_encode(static::extractParamsFromOffer($offer));
            if (! $model->save()) {
                throw new Exception('Ошибка при сохранении товара.');
            }

            $rel = new CatToItem();
            $rel->item_id = $model->id;
            $rel->category_id = (string) $offer->categoryId;
            if (! $rel->save()) {
                throw new Exception('Ошибка при сохранении связывании категории и товара.');
            }
        }

        return true;
    }


    public static function extractParamsFromOffer($offer)
    {
        $params = [];
        foreach ($offer->param as $param) {
            $params[(string) $param['name']] = (string) $param;
        }

        return $params;
    }


    public function getCategory()
    {
        return $this->hasOne(Category::class, ['original_id' => 'category_id'])
            ->viaTable(CatToItem::tableName(), ['item_id' => 'id']);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Items;
use Yii;
use yii\data\Pagination;
use yii\web\Controller;


class SiteController extends Controller
{

    public function actionIndex()
    {
        $id = Yii::$app->request->get('Category')['original_id'] ?: Category::DEFAULT_CATEGORY_ID;

        $query = Items::find()
            ->joinWith('category')
            ->where(['cat_to_item.category_id' => Category::getChildId($id)]);

        $countQuery = clone $query;
        $pages = new Pagination([
            'totalCount' => $countQuery->count(),
            'pageSize' => 3,
        ]);
        $items = $query->offset($pages->offset)->limit($pages->limit)->all();

        $categories = Category::find()
            ->innerJoinWith('catToItem', FALSE)
            ->all();

        return $this->render('index', compact('categories', 'items', 'id', 'pages'));
    }


    public function actionParse()
    {
        if (Yii::$app->request->get('file')) {
            $file = Yii::getAlias('@xml/' . Yii::$app->request->get('file'));
            if (file_exists($file)) {
                $xmlObject = simplexml_load_file($file);

                $transaction = Yii::$app->db->beginTransaction();
                try {
                    Category::loadFromXlm($xmlObject);
                    Items::extractOfferAndRelated($xmlObject);
                    $transaction->commit();
                    Yii::$app->session->setFlash('success', 'Данные сохранены!');
                }
                catch (\Exception $e) {
                    $transaction->rollBack();
                    Yii::$app->session->setFlash('error', 'Ошибка сохранения данных!');
                }
            }
        }

        return $this->render('parse');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header>
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-expand-md navbar-dark bg-dark fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav'],
        'items' => [
            ['label' => 'Товары', 'url' => ['/site/index']],
            ['label' => 'Парсинг', 'url' => ['/site/parse']],
        ],
    ]);
    NavBar::end();
    ?>
</header>

<main role="main" class="flex-shrink-0">
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>

        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer class="footer mt-auto py-3 text-muted">
    <div class="container">
        <p class="float-left">&copy; My Company <?= date('Y') ?></p>
        <p class="float-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/site/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\bootstrap4\LinkPager;
use app\models\Category;

$this->title = 'Товары';

$model = new Category();
$model->original_id = $id;
?>

<div class="site-index">
    <div class="row">
        <div class="col-md-4">
            <?php $form = ActiveForm::begin([
                'id' => 'category-form',
                'method' => 'get'
            ]); ?>

            <?php echo $form->field($model, 'original_id')
                ->dropDownList(array_column($categories, 'name', 'original_id'))
                ->label('Категория');
            ?>

            <div class="form-group">
                <?= Html::submitButton('Показать', ['class' => 'btn btn-primary btn-block', 'name' => 'category-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
        <div class="col-md-8" style="border-left: 1px solid black; ">
            <div class="row">
                <?php if (! empty($items)): ?>
                    <?php foreach ($items as $item): ?>
                        <div class="col-md-4">
                            <div class="item">
                                <div class="img">
                                    <img src="<?=$item->images; ?>" alt="Изображение" width="100%" class="img-thumbnail">
                                </div>
                                <h5>
                                    <?=$item->title; ?>
                                </h5>
                                <p><?= mb_strimwidth($item->description, 0, 100, '...'); ?></p>

                                <span class="badge badge-warning"><?=$item->category->name; ?></span>
                                <span class="badge badge-success"><?=$item->price; ?> ₴</span>

                            </div>
                        </div>
                    <?php endforeach; ?>
                    <div class="col-md-12">
                        <div id="pagelink">
                            <?= LinkPager::widget([
                                'pagination' => $pages,
                            ]); ?>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>

views/site/parse.php
<?php
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'Парсинг XML';
?>

<div class="container">
    <div class="row">
        <div class="col-md-2">
            <a href="<?=Url::to(['site/parse', 'file' => 'agent.xml']); ?>">Agent.xml</a>
        </div>
        <div class="col-md-2">
            <a href="<?=Url::to(['site/parse', 'file' => 'asos.xml']); ?>">Asos.xml</a>
        </div>
    </div>
</div>